### ISSUE TITLE
Alert is shown behind modal view

### ISSUE THREAD

**Issue by mj3052** [ondalabs/OLGhostAlertView#11] opened 2013-02-10 19:12 UTC
When making an init of OLGhostAlertView in a modal view it is shown in the viewcontroller "behind" the current one making it hidden for the user.

**Comment by radutzan** [comment] 2013-02-11 16:46
Thanks for reporting this. I'm marking it as a duplicate of #1.

**Closed as completed by radutzan** 2013-02-11 16:46 UTC
Labels: duplicate
